### ISSUE TITLE
Expose DEFAULT_SPLIT through command line parameter

### ISSUE THREAD

**Issue by oniltonmaciel** [bloomreach/s4cmd#20]
https://github.com/bloomreach/s4cmd/blob/92a9b532bf4583fb483a60d83e637dfa839f9797/s4cmd.py#L41

DEFAULT_SPLIT is hardcoded at 50MB.

I've got the feeling that for some larger file uploads it would be better to have a larger "split size". Maybe make some tweaking with `--num-threads` and this value could yield better results (faster uploads). 

I won't go into much details trying to explaining why I got this feeling, but if you want me to, I could explain more, or even fetch some data on this. 

Anyway, I think even if my feeling is not true, it would be very nice to have this value exposed to the user (through command line).
 
Note I am not suggesting changing default_split, but rather just being able to tweak this item.

PS: I'm not familiar with the code, but if you don't have time to do this, but are willing to receive pull requests, I could work on this (even if it could took more time for me to do this than it would for you :), ). 

Thanks in advance!

**Comment by viksit** [comment]
Makes sense. Would be good to get more data from you on this - can you post here?

Feel free to submit a pull request! See line 81 for an example of how a command line param overrides the default retry option,

```self.retry = opt.retry if opt else DEFAULT_RETRY```

**Comment by oniltonmaciel** [comment]
I opened a pull request with these changes:

About the data, unfortunately, right now I don't have enough time to go deeply on this issue, but I ran a quick test:

File ibdata1 with 9.2G.

After warming up, and running a few times the uploads, I got these results:

	ubuntu@machine:~$ time sudo ./s4cmd.py put -c 4 --multipart-split-size=500  -f /mnt/ibdata1 s3://MYBUCKET/percona/testing/
		                           
	real    2m17.153s
	user    0m38.846s
	sys     0m31.082s
	ubuntu@machine:~$ time sudo ./s4cmd.py put -c 4 --multipart-split-size=50 -f /mnt/ibdata1 s3://MYBUCKET/percona/testing/
		                            
	real    2m8.004s
	user    0m39.954s
	sys     0m30.142s

	ubuntu@machine:~$ time sudo ./s4cmd.py put -c 4 --multipart-split-size=10 -f /mnt/ibdata1 s3://MYBUCKET/percona/testing//testing/
		                            
	real    2m11.144s
	user    0m44.403s
	sys     0m32.982s

	ubuntu@machine:~$ time sudo ./s4cmd.py put -c 4 --multipart-split-size=100 -f /mnt/ibdata1 s3://MYBUCKET/percona/testing//testing/
		                           
	real    2m1.689s
	user    0m38.750s
	sys     0m31.462s

PS: I was running this test in a ec2 instance. I ommited some data for security reasons.

**Comment by linsomniac** [comment]
I'm not sure that your data supports your hypothesis.  Looks kind of like you have similar runtimes of ~2:09 with 8 seconds of variance.

This makes sense, as the overhead of the chunks is quite small, even at 5MB the overhead in terms of bytes is on the order of 0.01%.  And because it is threaded, the overhead in terms of connection setup/teardown latency is masked by other threads actively working while new connections are being made.

One thing to consider is that larger split sizes mean more to retransmit in the event a part fails, so there could be a large down-side in exchange for a small up-side.

In one of our internal tools I set the split size based on the file size: 5MB (the minimum) if the file is less than 50GB, and the file size divided by 10,000 (the maximum number of parts) if it is over 50GB.  This has proven extremely robust and completely saturates our network connection.
